services:
  - type: web
    name: mern-blog-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: /api
